In [7]:
from scipy.io import arff
import pandas as pd

data = arff.loadarff('data/5year.arff')
df = pd.DataFrame(data[0])

df.head()

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.088238,0.55472,0.01134,1.0205,-66.5200,0.342040,0.109490,0.57752,1.0881,0.32036,...,0.080955,0.275430,0.91905,0.002024,7.2711,4.7343,142.760,2.5568,3.2597,b'0'
1,-0.006202,0.48465,0.23298,1.5998,6.1825,0.000000,-0.006202,1.06340,1.2757,0.51535,...,-0.028591,-0.012035,1.00470,0.152220,6.0911,3.2749,111.140,3.2841,3.3700,b'0'
2,0.130240,0.22142,0.57751,3.6082,120.0400,0.187640,0.162120,3.05900,1.1415,0.67731,...,0.123960,0.192290,0.87604,0.000000,8.7934,2.9870,71.531,5.1027,5.6188,b'0'
3,-0.089951,0.88700,0.26927,1.5222,-55.9920,-0.073957,-0.089951,0.12740,1.2754,0.11300,...,0.418840,-0.796020,0.59074,2.878700,7.6524,3.3302,147.560,2.4735,5.9299,b'0'
4,0.048179,0.55041,0.10765,1.2437,-22.9590,0.000000,0.059280,0.81682,1.5150,0.44959,...,0.240400,0.107160,0.77048,0.139380,10.1180,4.0950,106.430,3.4294,3.3622,b'0'

In [8]:
df.columns = ['net profit / total assets ','total liabilities / total assets ','working capital / total assets ','current assets / short-term liabilities ','[(cash + short-term securities + receivables - short-term liabilities) / (operating expenses - depreciation)] * 365 ','retained earnings / total assets ','EBIT / total assets ','book value of equity / total liabilities ','sales / total assets ','equity / total assets ','(gross profit + extraordinary items + financial expenses) / total assets ','gross profit / short-term liabilities ','(gross profit + depreciation) / sales ','(gross profit + interest) / total assets ','(total liabilities * 365) / (gross profit + depreciation) ','(gross profit + depreciation) / total liabilities ','total assets / total liabilities ','gross profit / total assets ','gross profit / sales ','(inventory * 365) / sales ','sales (n) / sales (n-1) ','profit on operating activities / total assets ','net profit / sales ','gross profit (in 3 years) / total assets ','(equity - share capital) / total assets ','(net profit + depreciation) / total liabilities ','profit on operating activities / financial expenses ','working capital / fixed assets ','logarithm of total assets ','(total liabilities - cash) / sales ','(gross profit + interest) / sales ','(current liabilities * 365) / cost of products sold ','operating expenses / short-term liabilities ','operating expenses / total liabilities ','profit on sales / total assets ','total sales / total assets ','(current assets - inventories) / long-term liabilities ','constant capital / total assets ','profit on sales / sales ','(current assets - inventory - receivables) / short-term liabilities ','total liabilities / ((profit on operating activities + depreciation) * (12/365)) ','profit on operating activities / sales ','rotation receivables + inventory turnover in days ','(receivables * 365) / sales ','net profit / inventory ','(current assets - inventory) / short-term liabilities ','(inventory * 365) / cost of products sold ','EBITDA (profit on operating activities - depreciation) / total assets ','EBITDA (profit on operating activities - depreciation) / sales ','current assets / total liabilities ','short-term liabilities / total assets ','(short-term liabilities * 365) / cost of products sold) ','equity / fixed assets ','constant capital / fixed assets ','working capital ','(sales - cost of products sold) / sales ','(current assets - inventory - short-term liabilities) / (sales - gross profit - depreciation) ','total costs /total sales ','long-term liabilities / equity ','sales / inventory ','sales / receivables ','(short-term liabilities *365) / sales ','sales / short-term liabilities ','sales / fixed assets', 'bankruptcy']

In [9]:
df.head()

,net profit / total assets,total liabilities / total assets,working capital / total assets,current assets / short-term liabilities,[(cash + short-term securities + receivables - short-term liabilities) / (operating expenses - depreciation)] * 365,retained earnings / total assets,EBIT / total assets,book value of equity / total liabilities,sales / total assets,equity / total assets,...,(sales - cost of products sold) / sales,(current assets - inventory - short-term liabilities) / (sales - gross profit - depreciation),total costs /total sales,long-term liabilities / equity,sales / inventory,sales / receivables,(short-term liabilities *365) / sales,sales / short-term liabilities,sales / fixed assets,bankruptcy
0,0.088238,0.55472,0.01134,1.0205,-66.5200,0.342040,0.109490,0.57752,1.0881,0.32036,...,0.080955,0.275430,0.91905,0.002024,7.2711,4.7343,142.760,2.5568,3.2597,b'0'
1,-0.006202,0.48465,0.23298,1.5998,6.1825,0.000000,-0.006202,1.06340,1.2757,0.51535,...,-0.028591,-0.012035,1.00470,0.152220,6.0911,3.2749,111.140,3.2841,3.3700,b'0'
2,0.130240,0.22142,0.57751,3.6082,120.0400,0.187640,0.162120,3.05900,1.1415,0.67731,...,0.123960,0.192290,0.87604,0.000000,8.7934,2.9870,71.531,5.1027,5.6188,b'0'
3,-0.089951,0.88700,0.26927,1.5222,-55.9920,-0.073957,-0.089951,0.12740,1.2754,0.11300,...,0.418840,-0.796020,0.59074,2.878700,7.6524,3.3302,147.560,2.4735,5.9299,b'0'
4,0.048179,0.55041,0.10765,1.2437,-22.9590,0.000000,0.059280,0.81682,1.5150,0.44959,...,0.240400,0.107160,0.77048,0.139380,10.1180,4.0950,106.430,3.4294,3.3622,b'0'

In [10]:
df.bankruptcy.unique()

array([b'0', b'1'], dtype=object)

In [13]:
df.bankruptcy.value_counts()

b'0'    5500
b'1'     410
Name: bankruptcy, dtype: int64