In [1]:
import pandas as pd

In [13]:
df = pd.read_excel("Case Study_Fruit Juices.xlsx")

In [14]:
df

,resp_id,Brand,Aware,imagery_1,imagery_2,imagery_3,imagery_4,imagery_5,imagery_6,imagery_7,imagery_8,imagery_9,imagery_10,OL,attitude_1,attitude_2,attitude_3,attitude_4,attitude_5
0,1,1,1,3,3,3,3,3,2,2,1,2,4,3,2,2,2,3,3
1,1,2,1,3,1,3,1,2,5,4,3,3,3,3,2,2,2,3,3
2,1,3,1,3,1,3,2,2,3,3,3,3,3,3,2,2,2,3,3
3,2,1,1,4,2,3,2,2,2,3,2,2,3,3,4,4,3,2,2
4,2,2,1,2,3,1,3,2,4,2,2,1,2,2,4,4,3,2,2
5,2,3,1,2,2,3,1,2,1,3,2,3,2,3,4,4,3,2,2
6,3,1,1,1,1,2,1,2,3,3,3,3,2,3,3,3,2,2,2
7,3,2,1,3,2,2,3,2,4,4,3,3,3,3,3,3,2,2,2
8,3,3,1,2,3,2,3,2,4,3,3,2,2,3,3,3,2,2,2
9,4,1,1,4,4,3,4,4,4,3,3,2,4,4,1,1,1,3,3
10,4,2,1,3,1,3,1,2,2,4,3,4,3,3,1,1,1,3,3
11,4,3,1,3,3,3,4,3,2,3,3,3,2,3,1,1,1,3,3
12,5,1,1,4,2,3,2,2,2,2,1,2,3,3,2,1,3,2,3
13,5,2,1,2,3,3,3,4,2,1,3,1,3,3,2,1,3,2,3
14,5,3,1,1,3,1,2,2,2,2,1,1,1,2,2,1,3,2,3
15,6,1,1,2,2,2,2,2,3,2,2,2,3,3,3,2,2,2,3
16,6,2,1,4,3,4,4,4,2,2,2,3,4,4,3,2,2,2,3
17,6,3,1,4,3,3,3,2,4,3,3,3,3,4,3,2,2,2,3
18,7,1,1,3,4,4,4,4,2,4,2,3,3,4,4,4,3,2,2
19,7,2,1,2,2,1,1,1,5,4,4,3,2,3,4,4,3,2,2
20,7,3,1,2,1,2,2,1,2,4,2,3,1,3,4,4,3,2,2
21,8,1,1,4,3,3,4,3,4,4,3,3,3,4,3,3,2,3,3
22,8,2,1,3,3,4,3,4,2,1,2,1,4,3,3,3,2,3,3
23,8,3,1,3,3,2,2,2,3,3,3,2,3,3,3,3,2,3,3
24,9,1,1,2,1,2,1,2,2,1,2,1,3,2,4,3,4,1,2
25,9,2,1,4,4,3,4,4,3,4,4,3,4,4,4,3,4,1,2
26,9,3,1,3,1,3,2,2,3,3,3,3,3,3,4,3,4,1,2
27,10,1,1,3,1,2,2,1,3,5,3,4,2,3,4,4,4,2,2
28,10,2,1,3,2,2,2,2,4,4,3,3,3,3,4,4,4,2,2
29,10,3,1,3,1,2,2,1,3,3,1,2,2,2,4,4,4,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,491,1,1,3,1,3,2,2,4,4,2,3,3,3,2,1,2,2,3
1471,491,2,1,3,3,3,2,2,3,4,4,4,2,3,2,1,2,2,3
1472,491,3,1,3,1,3,1,2,3,2,2,2,3,3,2,1,2,2,3
1473,492,1,1,3,3,3,3,3,2,2,2,1,4,3,3,2,4,2,3
1474,492,2,1,3,1,2,2,1,3,4,3,3,2,3,3,2,4,2,3
1475,492,3,1,2,1,1,2,1,2,2,1,1,2,2,3,2,4,2,3
1476,493,1,1,2,1,3,1,2,3,2,2,2,2,2,5,4,4,1,2
1477,493,2,1,2,4,3,3,4,3,2,3,2,3,3,5,4,4,1,2
1478,493,3,1,2,2,2,1,2,2,2,1,1,3,2,5,4,4,1,2
1479,494,1,1,3,2,2,1,1,2,2,1,2,2,2,2,1,2,3,4
1480,494,2,1,2,3,2,2,2,3,3,2,3,1,3,2,1,2,3,4
1481,494,3,1,2,3,3,4,4,2,3,2,2,3,3,2,1,2,3,4
1482,495,1,1,2,1,2,1,2,3,2,2,1,3,3,2,2,3,4,4
1483,495,2,1,3,2,3,1,2,4,5,4,4,3,4,2,2,3,4,4
1484,495,3,1,2,2,2,3,2,1,2,1,2,1,2,2,2,3,4,4
1485,496,1,1,5,4,4,4,4,3,3,3,3,4,4,3,4,2,3,2
1486,496,2,1,3,2,2,3,2,2,2,1,1,3,2,3,4,2,3,2
1487,496,3,1,3,1,3,1,2,2,3,2,3,3,3,3,4,2,3,2
1488,497,1,1,4,3,3,3,3,4,3,4,2,4,3,3,2,4,2,3
1489,497,2,1,4,3,3,4,3,3,3,1,2,3,3,3,2,4,2,3
1490,497,3,1,1,1,2,2,2,2,1,2,2,2,2,3,2,4,2,3
1491,498,1,1,4,3,4,2,3,3,3,3,4,4,3,4,3,3,2,3
1492,498,2,1,2,1,2,2,2,2,2,1,1,3,2,4,3,3,2,3
1493,498,3,1,4,3,3,3,2,2,4,3,4,3,4,4,3,3,2,3
1494,499,1,1,2,2,2,3,2,4,4,2,3,1,3,2,2,2,4,4
1495,499,2,1,3,2,3,2,3,4,2,2,1,4,3,2,2,2,4,4
1496,499,3,1,2,2,2,2,2,4,2,3,2,2,3,2,2,2,4,4
1497,500,1,1,3,3,3,4,3,2,4,4,4,2,3,1,2,1,3,2
1498,500,2,1,3,1,2,1,1,1,2,1,2,2,2,1,2,1,3,2
1499,500,3,1,2,2,1,2,2,3,2,1,1,2,2,1,2,1,3,2

In [15]:
dfa = df.drop(columns=['resp_id','Brand', 'Aware', 'OL'])

In [16]:
dfa

,imagery_1,imagery_2,imagery_3,imagery_4,imagery_5,imagery_6,imagery_7,imagery_8,imagery_9,imagery_10,attitude_1,attitude_2,attitude_3,attitude_4,attitude_5
0,3,3,3,3,3,2,2,1,2,4,2,2,2,3,3
1,3,1,3,1,2,5,4,3,3,3,2,2,2,3,3
2,3,1,3,2,2,3,3,3,3,3,2,2,2,3,3
3,4,2,3,2,2,2,3,2,2,3,4,4,3,2,2
4,2,3,1,3,2,4,2,2,1,2,4,4,3,2,2
5,2,2,3,1,2,1,3,2,3,2,4,4,3,2,2
6,1,1,2,1,2,3,3,3,3,2,3,3,2,2,2
7,3,2,2,3,2,4,4,3,3,3,3,3,2,2,2
8,2,3,2,3,2,4,3,3,2,2,3,3,2,2,2
9,4,4,3,4,4,4,3,3,2,4,1,1,1,3,3
10,3,1,3,1,2,2,4,3,4,3,1,1,1,3,3
11,3,3,3,4,3,2,3,3,3,2,1,1,1,3,3
12,4,2,3,2,2,2,2,1,2,3,2,1,3,2,3
13,2,3,3,3,4,2,1,3,1,3,2,1,3,2,3
14,1,3,1,2,2,2,2,1,1,1,2,1,3,2,3
15,2,2,2,2,2,3,2,2,2,3,3,2,2,2,3
16,4,3,4,4,4,2,2,2,3,4,3,2,2,2,3
17,4,3,3,3,2,4,3,3,3,3,3,2,2,2,3
18,3,4,4,4,4,2,4,2,3,3,4,4,3,2,2
19,2,2,1,1,1,5,4,4,3,2,4,4,3,2,2
20,2,1,2,2,1,2,4,2,3,1,4,4,3,2,2
21,4,3,3,4,3,4,4,3,3,3,3,3,2,3,3
22,3,3,4,3,4,2,1,2,1,4,3,3,2,3,3
23,3,3,2,2,2,3,3,3,2,3,3,3,2,3,3
24,2,1,2,1,2,2,1,2,1,3,4,3,4,1,2
25,4,4,3,4,4,3,4,4,3,4,4,3,4,1,2
26,3,1,3,2,2,3,3,3,3,3,4,3,4,1,2
27,3,1,2,2,1,3,5,3,4,2,4,4,4,2,2
28,3,2,2,2,2,4,4,3,3,3,4,4,4,2,2
29,3,1,2,2,1,3,3,1,2,2,4,4,4,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,3,1,3,2,2,4,4,2,3,3,2,1,2,2,3
1471,3,3,3,2,2,3,4,4,4,2,2,1,2,2,3
1472,3,1,3,1,2,3,2,2,2,3,2,1,2,2,3
1473,3,3,3,3,3,2,2,2,1,4,3,2,4,2,3
1474,3,1,2,2,1,3,4,3,3,2,3,2,4,2,3
1475,2,1,1,2,1,2,2,1,1,2,3,2,4,2,3
1476,2,1,3,1,2,3,2,2,2,2,5,4,4,1,2
1477,2,4,3,3,4,3,2,3,2,3,5,4,4,1,2
1478,2,2,2,1,2,2,2,1,1,3,5,4,4,1,2
1479,3,2,2,1,1,2,2,1,2,2,2,1,2,3,4
1480,2,3,2,2,2,3,3,2,3,1,2,1,2,3,4
1481,2,3,3,4,4,2,3,2,2,3,2,1,2,3,4
1482,2,1,2,1,2,3,2,2,1,3,2,2,3,4,4
1483,3,2,3,1,2,4,5,4,4,3,2,2,3,4,4
1484,2,2,2,3,2,1,2,1,2,1,2,2,3,4,4
1485,5,4,4,4,4,3,3,3,3,4,3,4,2,3,2
1486,3,2,2,3,2,2,2,1,1,3,3,4,2,3,2
1487,3,1,3,1,2,2,3,2,3,3,3,4,2,3,2
1488,4,3,3,3,3,4,3,4,2,4,3,2,4,2,3
1489,4,3,3,4,3,3,3,1,2,3,3,2,4,2,3
1490,1,1,2,2,2,2,1,2,2,2,3,2,4,2,3
1491,4,3,4,2,3,3,3,3,4,4,4,3,3,2,3
1492,2,1,2,2,2,2,2,1,1,3,4,3,3,2,3
1493,4,3,3,3,2,2,4,3,4,3,4,3,3,2,3
1494,2,2,2,3,2,4,4,2,3,1,2,2,2,4,4
1495,3,2,3,2,3,4,2,2,1,4,2,2,2,4,4
1496,2,2,2,2,2,4,2,3,2,2,2,2,2,4,4
1497,3,3,3,4,3,2,4,4,4,2,1,2,1,3,2
1498,3,1,2,1,1,1,2,1,2,2,1,2,1,3,2
1499,2,2,1,2,2,3,2,1,1,2,1,2,1,3,2

In [17]:
from factor_analyzer import FactorAnalyzer

In [18]:
fa = FactorAnalyzer()

In [21]:
fa.analyze(dfa, 3, rotation=None)

In [22]:
fa.loadings

             Factor1   Factor2
imagery_1   0.732420 -0.043145
imagery_2   0.676145 -0.054466
imagery_3   0.852896 -0.034731
imagery_4   0.678476 -0.074678
imagery_5   0.872929 -0.051629
imagery_6   0.110739 -0.001623
imagery_7   0.224820  0.028818
imagery_8   0.323344  0.004140
imagery_9   0.218816  0.027881
imagery_10  0.793598 -0.043996
attitude_1  0.076520  0.871168
attitude_2  0.079685  0.711031
attitude_3  0.074305  0.703362
attitude_4 -0.030677 -0.654203
attitude_5 -0.037410 -0.516122